apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-demo
  region: us-east-1
  version: "1.25"

managedNodeGroups:
  - name: primary
    instanceType: t2.small
    minSize: 3
    maxSize: 4
    spot: true
